package com.glg204.fep.application.LoanApplication;

import com.glg204.fep.application.RefundApplication.RefundService;
import com.glg204.fep.domain.LoanDomain.Loan;
import com.glg204.fep.domain.LoanDomain.LoanStatus;
import com.glg204.fep.domain.UserDomain.User;
import com.glg204.fep.domain.UserDomain.UserRole;
import com.glg204.fep.infrastructure.LoanInfrastructure.LoanRepository;
import com.glg204.fep.infrastructure.UserInfrastructure.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.MockedStatic;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContext;
import org.springframework.security.core.context.SecurityContextHolder;

import java.math.BigDecimal;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

public class LoanServiceTest {

    private LoanRepository loanRepository;
    private UserRepository userRepository;
    private LoanNotificationService loanNotificationService;
    private RefundService refundService;
    private LoanService loanService;

    @BeforeEach
    void setup() {
        loanRepository = mock(LoanRepository.class);
        userRepository = mock(UserRepository.class);
        loanNotificationService = mock(LoanNotificationService.class);
        refundService = mock(RefundService.class);
        loanService = new LoanService(loanRepository, userRepository, loanNotificationService, refundService);
    }

    @Test
    void shouldCreateLoanWithhSuccess() {
        User lender = new User();
        lender.setId(1L);
        lender.setEmail("lender@example.com");
        lender.setFirstName("Jane");

        LoanRequestDTO request = LoanRequestDTO.builder()
                .amount(BigDecimal.valueOf(1000))
                .interestRate(5.0)
                .durationInMonths(12)
                .status(LoanStatus.PENDING)
                .borrowerId(2L)
                .build();

        LoanResponseDTO response = loanService.createLoan(request, lender);

        assertEquals(BigDecimal.valueOf(1000), response.getAmount());
        assertEquals(5.0, response.getInterestRate());
        // createLoan forces the PENDING status and never assigns a borrower.
        assertEquals("PENDING", response.getStatus());
        assertNull(response.getBorrower());

        // The reference is generated by LoanDomainService.generateReference():
        // "LN-<yyyyMMdd>-<HHmmssSSS>-<4 hex chars>". It cannot be asserted as a
        // fixed value, only as a pattern.
        assertNotNull(response.getReference());
        assertTrue(response.getReference().matches("LN-\\d{8}-\\d{9}-[0-9A-F]{4}"));

        verify(loanRepository).save(any(Loan.class));

        // The creation mail now goes to the lender, not the borrower.
        verify(loanNotificationService).sendLoanRequestCreatedMail(
                eq("lender@example.com"),
                eq("Jane"),
                argThat(reference -> reference != null && reference.startsWith("LN-"))
        );

        // The repayment schedule is delegated to RefundService.
        verify(refundService).generateRefundsForLoan(any(Loan.class), any(BigDecimal.class));
    }

    @Test
    void shouldThrowExceptionWhenBorrowerNotFoundOnUpdate() {
        // createLoan no longer looks the borrower up (it sets it to null), so the
        // "borrower not found" contract is only enforced by updateLoan.
        Loan loan = new Loan();
        loan.setId(1L);

        LoanRequestDTO request = LoanRequestDTO.builder()
                .amount(BigDecimal.valueOf(1000))
                .interestRate(5.0)
                .durationInMonths(12)
                .status(LoanStatus.IN_PROGRESS)
                .borrowerId(99L)
                .build();

        when(loanRepository.findById(1L)).thenReturn(Optional.of(loan));
        when(userRepository.findById(99L)).thenReturn(Optional.empty());

        assertThrows(NoSuchElementException.class, () -> loanService.updateLoan(1L, request));
    }

    @Test
    void shouldReturnAllLoans() {
        Loan loan = new Loan();
        loan.setId(1L);
        loan.setAmount(BigDecimal.valueOf(500));
        loan.setInterestRate(3.0);
        loan.setDurationInMonths(6);
        loan.setStatus(LoanStatus.IN_PROGRESS);

        when(loanRepository.findAll()).thenReturn(List.of(loan));

        List<LoanResponseDTO> loans = loanService.getAllLoans();

        assertEquals(1, loans.size());
        assertEquals(500, loans.get(0).getAmount().intValue());
    }

    @Test
    void shouldReturnLoansByUser() {
        User user = new User();
        user.setId(1L);

        Loan loan = new Loan();
        loan.setId(2L);
        loan.setLender(user);
        loan.setBorrower(user);
        loan.setAmount(BigDecimal.valueOf(700));

        try (MockedStatic<SecurityContextHolder> mocked = mockStatic(SecurityContextHolder.class)) {
            SecurityContext context = mock(SecurityContext.class);
            Authentication auth = mock(Authentication.class);
            when(SecurityContextHolder.getContext()).thenReturn(context);
            when(context.getAuthentication()).thenReturn(auth);
            when(auth.getPrincipal()).thenReturn(user);

            when(loanRepository.findByLenderOrBorrower(user, user)).thenReturn(List.of(loan));

            List<LoanResponseDTO> result = loanService.getLoansByUser();

            assertEquals(1, result.size());
            assertEquals(700, result.get(0).getAmount().intValue());
        }
    }

    @Test
    void shouldUpdateLoanWithSuccess() {
        Loan loan = new Loan();
        loan.setId(1L);

        User borrower = new User();
        borrower.setId(2L);

        LoanRequestDTO request = LoanRequestDTO.builder()
                .amount(BigDecimal.valueOf(1500))
                .interestRate(4.5)
                .durationInMonths(24)
                .status(LoanStatus.IN_PROGRESS)
                .borrowerId(2L)
                .build();

        when(loanRepository.findById(1L)).thenReturn(Optional.of(loan));
        when(userRepository.findById(2L)).thenReturn(Optional.of(borrower));

        LoanResponseDTO updated = loanService.updateLoan(1L, request);

        assertEquals(1500, updated.getAmount().intValue());
        assertEquals(4.5, updated.getInterestRate());
        assertEquals("IN_PROGRESS", updated.getStatus());
    }

    @Test
    void shouldThrowExceptionWhenUpdatingNonexistingLoan() {
        when(loanRepository.findById(99L)).thenReturn(Optional.empty());

        LoanRequestDTO request = LoanRequestDTO.builder().borrowerId(1L).build();

        assertThrows(NoSuchElementException.class, () -> loanService.updateLoan(99L, request));
    }

    @Test
    void shouldDeleteLoanSuccessfully() {
        when(loanRepository.existsById(1L)).thenReturn(true);

        loanService.deleteLoan(1L);

        verify(loanRepository).deleteById(1L);
    }

    @Test
    void shouldThrowExceptionWhenDeletingNonexistentLoan() {
        when(loanRepository.existsById(99L)).thenReturn(false);

        assertThrows(NoSuchElementException.class, () -> loanService.deleteLoan(99L));
    }
}
